### ISSUE TITLE
client.take() order guarantee?

### ISSUE THREAD

**Issue by rtorrero** [auth0/limitd#52]
Is there guarantee that if two clients call the take() method when there are no tokens available that they will be allowed to continue in the same order they requested?

**Comment by jfromaniello** [comment]
I think you mean `wait`, if two clients call take and there are not any tokens both will get `conformant: false`

**Comment by dschenkelman** [comment]
@rtorrero: no, there are no guarantees, even if they are using the same bucket. If the current code ensures that, it is not an implementation decision, just a coincidence.
