### ISSUE TITLE
Suggestions for HA deployment?

### ISSUE THREAD

**Issue by rtorrero** [auth0/limitd#53]
Is there any way of deploying multiple limitd servers and make the client switch from one server to another in case the first one goes down?

Thanks!

**Comment by jfromaniello** [comment]
Sorry for the long delay! I missed the email.

Yes, the limitd client supports an array of "hosts":
https://github.com/limitd/node-client

The order matters. The first host will be the preferred always.

If you use the leveldb backend there isn't way to replicate data at the server level. You can use the redis backend.
